import {
  ProductStatus,
  Size,
  TargetAudience,
} from "@prisma/client";

const sampleData = {
  users: [
    {
      name: "Admin",
      email: "admin@example.com",
      password: "123456",
      role: "admin",
    },
  ],
  products: [
    {
      name: "Blue T-shirt",
      slug: "blue-t-shirt",
      category: ["t-shirt"],
      description: "Comfortable blue T-shirt for men.",
      images: ["/images/sample-products/p1.jpg"],
      price: 29.99,
      targetAudience: TargetAudience.MEN,
      rating: 4.5,
      numReviews: 10,
      stock: 1,
      size: [Size.M],
      color: "Blue",
      status: ProductStatus.LOW_STOCK,
      isNew: true,
      bestSeller: true,
    },
    {
      name: "White T-Shirt",
      slug: "white-t-shirt",
      category: ["t-shirt"],
      description: "Elegant white shirt for women.",
      images: ["/images/sample-products/p2.jpg"],
      price: 49.99,
      targetAudience: TargetAudience.WOMEN,
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      size: [Size.S, Size.M],
      color: "White",
      status: ProductStatus.IN_STOCK,
      isNew: true,
      bestSeller: true,
    },
    {
      name: "Orange Sweatshirt",
      slug: "orange-sweatshirt",
      category: ["sweatshirt"],
      description: "Cozy orange sweatshirt for women.",
      images: ["/images/sample-products/p3.jpg"],
      price: 59.99,
      targetAudience: TargetAudience.WOMEN,
      rating: 4.3,
      numReviews: 5,
      stock: 8,
      size: [Size.S, Size.M, Size.L],
      color: "orange",
      status: ProductStatus.IN_STOCK,
      isNew: true,
    },
    {
      name: "Shirt Mini Dress",
      slug: "shirt-mini-dress",
      category: ["dress", "shirt"],
      description: "Chic shirt mini dress for women.",
      images: ["/images/sample-products/p4.jpg"],
      price: 69.99,
      targetAudience: TargetAudience.WOMEN,
      rating: 4.0,
      numReviews: 6,
      stock: 5,
      size: [Size.S, Size.M, Size.L],
      color: "white",
      status: ProductStatus.IN_STOCK,
    },
    {
      name: "Midi Dress",
      slug: "midi-dress",
      category: ["dress"],
      description: "Elegant midi dress for women.",
      images: ["/images/sample-products/p5.jpg"],
      price: 79.99,
      targetAudience: TargetAudience.WOMEN,
      rating: 4.7,
      numReviews: 12,
      stock: 4,
      size: [Size.S, Size.M, Size.L],
      color: "grey",
      status: ProductStatus.IN_STOCK,
      discountPercent: 50,
    },
  ],
};

export default sampleData;
