import {
  ProductStatus,
  TargetAudience,
} from "@/lib/schema";

const sampleData = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: "123456",
      role: "admin",
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: "123456",
      role: "user",
    },
  ],
  products: [
    {
      id: "1",
      name: "Blue T-shirt",
      slug: "blue-t-shirt",
      category: ["t-shirt"],
      description: "Comfortable blue T-shirt for men.",
      images: ["/images/sample-products/p1.jpg"],
      price: 29.99,
      targetAudience: TargetAudience.MEN,
      rating: 4.5,
      numReviews: 10,
      stock: 1,
      isFeatured: true,
      size: ["M"],
      color: "Blue",
      status: ProductStatus.LOW_STOCK,
      isNew: true,
      bestSeller: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "2",
      name: "White T-Shirt",
      slug: "white-t-shirt",
      category: ["t-shirt"],
      description: "Elegant white shirt for women.",
      images: ["/images/sample-products/p2.jpg"],
      price: 49.99,
      targetAudience: TargetAudience.WOMEN,
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: false,
      size: ["S", "M"],
      color: "White",
      status: ProductStatus.IN_STOCK,
      isNew: true,
      bestSeller: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "3",
      name: "Orange Sweatshirt",
      slug: "orange-sweatshirt",
      category: ["sweatshirt"],
      description: "Cozy orange sweatshirt for women.",
      images: ["/images/sample-products/p3.jpg"],
      price: 59.99,
      targetAudience: TargetAudience.WOMEN,
      rating: 4.3,
      numReviews: 5,
      stock: 8,
      isFeatured: true,
      size: ["S", "M", "L", "XL"],
      color: "orange",
      status: ProductStatus.IN_STOCK,
      isNew: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "4",
      name: "Shirt Mini Dress",
      slug: "shirt-mini-dress",
      category: ["dress", "shirt"],
      description: "Chic shirt mini dress for women.",
      images: ["/images/sample-products/p4.jpg"],
      price: 69.99,
      targetAudience: TargetAudience.WOMEN,
      rating: 4.0,
      numReviews: 6,
      stock: 5,
      isFeatured: false,
      size: ["S", "M", "L", "XL"],
      color: "white",
      status: ProductStatus.IN_STOCK,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "5",
      name: "Midi Dress",
      slug: "midi-dress",
      category: ["dress"],
      description: "Elegant midi dress for women.",
      images: ["/images/sample-products/p5.jpg"],
      price: 79.99,
      targetAudience: TargetAudience.WOMEN,
      rating: 4.7,
      numReviews: 12,
      stock: 4,
      isFeatured: true,
      size: ["S", "M", "L", "XL"],
      color: "grey",
      status: ProductStatus.IN_STOCK,
      discountPercent: 50,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
};

export default sampleData;
