const sampleData = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: "123456",
      role: "admin",
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: "123456",
      role: "user",
    },
  ],
  products: [
    {
      id: 1,
      name: "Blue T-shirt",
      slug: "blue-t-shirt",
      category: "t-shirt",
      description: "Comfortable blue T-shirt for men.",
      images: ["/images/sample-products/p1.jpg"],
      price: 29.99,
      targetAudience: "MEN",
      rating: 4.5,
      numReviews: 10,
      stock: 1,
      isFeatured: true,
      size: "M",
      color: "Blue",
      status: "LOW_STOCK",
      isNew: true,
      bestSeller: true,
    },
    {
      id: 2,
      name: "White T-Shirt",
      slug: "white-t-shirt",
      category: "t-shirt",
      description: "Elegant white shirt for women.",
      images: ["/images/sample-products/p2.jpg"],
      price: 49.99,
      targetAudience: "WOMEN",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: false,
      size: "S,M",
      color: "White",
      status: "IN_STOCK",
      isNew: true,
      bestSeller: true,
    },
    {
      id: 3,
      name: "Orange Sweatshirt",
      slug: "orange-sweatshirt",
      category: "sweatshirt",
      description: "Cozy orange sweatshirt for women.",
      images: ["/images/sample-products/p3.jpg"],
      price: 59.99,
      targetAudience: "WOMEN",
      rating: 4.3,
      numReviews: 5,
      stock: 8,
      isFeatured: true,
      size: "S,M,L,XL",
      color: "orange",
      status: "IN_STOCK",
      isNew: true,
    },
    {
      id: 4,
      name: "Shirt Mini Dress",
      slug: "shirt-mini-dress",
      category: "dress",
      description: "Chic shirt mini dress for women.",
      images: ["/images/sample-products/p4.jpg"],
      price: 69.99,
      targetAudience: "WOMEN",
      rating: 4.0,
      numReviews: 6,
      stock: 5,
      isFeatured: false,
      size: "S,M,L,XL",
      color: "white",
      status: "IN_STOCK",
    },
    {
      id: 5,
      name: "Midi Dress",
      slug: "midi-dress",
      category: "dress",
      description: "Elegant midi dress for women.",
      images: ["/images/sample-products/p5.jpg"],
      price: 79.99,
      targetAudience: "WOMEN",
      rating: 4.7,
      numReviews: 12,
      stock: 4,
      isFeatured: true,
      size: "S,M,L,XL",
      color: "grey",
      status: "IN_STOCK",
      discountPercent: 50,
    },
  ],
};

export default sampleData;
